### ISSUE TITLE
GUI Mockup: Contacts

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#13]
could look like this:
![contacts](https://cloud.githubusercontent.com/assets/840070/25556057/e465583e-2cf5-11e7-94be-331f00167cf6.png)

- sidebar shows contacts alphabetically
- main area shows info about contact with call or chat option

**Comment by Elv13** [comment]
#### Progress/roadmap/tasks tracker:

 - [X] Fix the availability of actions (like add contact, edit contact) for registered usernames
 - [X] Save relevant data in the history database to avoid DNS name vs. registered name ambiguity
 - [X] Add registerednames to the deduplication index (otherwise adding a contact on the ringId wont be visible on the registered name based history/bookmark/call/certificate elements)
 - [X] Fix the contact editing from the history dock (upstream changes broke it)
 - [X] Fix showing the old fallback contact dialog when relevant (for testing the backend, before writing the one described above)
 - [X] Ensure that the Ring-daemon correctly update `getCallDetails` when a name is used to place a call
 - [X] Bring the (currently default) vCard backend on par with the Akonadi when it comes to contacts*
 - [X] Implement a "view contact" pane that doesn't depend on Akonadi
 - [X] Add "New contact" to the main menu
 - [X] Port the old QtWidget edit contact/profile dialog to the modern age (and QML, for consistency)
    - [X] Write a mockup (it was part of the "demo" wizard last page, see that youtube video)
    - [ ] Add the ability to add registered names with validation (auto import RingId)
    - [X] Add an Actionmodel to the contact and each ContactMethod (RingId/phone_numbers/URIs/hostnames)
 - [ ] Enable the new widget in the wizard (the edit profile and edit contact use the same code)
 - [X] Integrate the view/edit contact views into the main GUI (overlap issue #12)
 - [X Write a QIconEngine because apparently I have to since everything is otherwise pixelated...
 - [ ] Deduplicate the ring daemon own version of the contact with the local/akonadi ones (discussed with upstream)

#### Milestones:

 - [X] Implement all contact management features for the vCard backend
 - [ ] Make sure I didn't break the Akonadi code doing the provious milestone
 - [X] Implement the new GUI as suggested (requires the 2 previous milestones to be completed)
 - [ ] Enable ContactRequests (once upstream is ready to enable them in other clients)

\* The Akonadi backend has more contact management features, but they get disabled when using the vCard backend. I will have to implement the others "capabilities" to the vCard backend unless you want me to use Akonadi (you already said you didn't).

Screenshot of the bussiness logic side (old GUI)

![pick11](https://cloud.githubusercontent.com/assets/340384/25650206/6029512c-2fa9-11e7-928b-79a4aa8b72e8.png)

![pick11](https://cloud.githubusercontent.com/assets/340384/25650208/627ab7e0-2fa9-11e7-85d2-b56e7b6e8fb6.png)

![pick11](https://cloud.githubusercontent.com/assets/340384/25650210/6558b91c-2fa9-11e7-8813-f1c3e6025f20.png)

![pick11](https://cloud.githubusercontent.com/assets/340384/25650225/7e6592cc-2fa9-11e7-9faa-e40af0968f4b.png)

**Comment by star-buck** [comment]
Screenshots look promising, and yeah, lets not use anything Akonadi right now, as it is quite unclear what is the future of KDE Pim with two projects competing.
We could discuss what makes sense with anyone at the Akademy, but keep it independent for now and possibly do a connector or bridge later.

**Comment by Elv13** [comment]
As promised, here's my update. It is very early. 90% of the work is getting the backend into shape for the timeline "mega feature". But contacts is progressing as well.

![image](https://cloud.githubusercontent.com/assets/340384/25899430/d1861c4c-355d-11e7-9c1c-63ebfd78d3e8.png)

Please don't mind the colors and general ugliness. I am not working on "cool looking UI" yet. It is more about getting everything working well together. I will push this version for (early) testing after updating the GitHub issues. I don't think it is mature enough to really test yet, but it's "good enough" for playing with it.

**Comment by star-buck** [comment]
Looks really good feature wise.

**Comment by Elv13** [comment]
[Weekly update]

As this is interwinded with the new timeline UX, I don't have a spectacular screenshot to show, but this is mostly done. Some important corner cases still need to be handled (like persisting new contacts...), but overall it works. Saving works. Most of the code is under the hood and the GUI is still not very nice, but overall it's getting there.

**Comment by Elv13** [comment]
(the feature is unchanged since last week, it is now awaiting testing)

**Comment by Elv13** [comment]
Newly added:

 * Support for setting the photo from the webcam, camara or file (with a very basic GUI editor)
 * Support for addresses
 * Support for multiple phone number or Ring accounts
    * Call each numbers directly from the GUI

![image](https://cloud.githubusercontent.com/assets/340384/26713205/5910c936-4739-11e7-83f2-db1bdec139c2.png)

**Comment by star-buck** [comment]
@Elv13 : Please provide non-TRON-like screenshots with standard KDE Breeze theme LIGHT version.
